name: recipes_appv2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  package_info_plus: ^8.3.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  skeletonizer: ^2.0.1
  youtube_player_flutter: ^9.1.1
  youtube_player_iframe: ^5.2.1

dev_dependencies:
  build_runner: ^2.4.15
  change_app_package_name: ^1.5.0
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
